name: landsat-product-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.0.13
  - mystmd
  - jupyterlab-myst
  - xarray
  - pygmt
  - pystac-client
  - pyproj
  - pandas
  - geopandas
  - intake=0.7.0
  - intake-esm=2024.2.6
  - earthaccess
  - scikit-learn
  - ipywidgets
  - tqdm
  - boto3=1.39.8
  - rasterio
  - dask
  - rioxarray=0.19.0
  - cartopy
  - scipy
  - shapely
  - statsmodels
  - cycler
  - pytest
  - matplotlib
  - ipympl
  - geoviews
  - hvplot
  - seaborn
  - metpy
  - pip
